# 随机字符串
com:
  value: ${random.value}
  # 随机int
  int: ${random.int}
  # 10 以内的随机数
  test: ${random.long(10)}
  # 10 - 20 的随机数
  test1: ${random.int[10,20]}


server:
  port: 8881

spring:
  application:
    name: centre
  jpa:
    database-platform: mysql
    databaseplatform: mysql
    databasePlatform: mysql
    database_paltfrom: mysql
  my-example:
    url:
      - http://example.com
      - http://spring.io
    url2: http://example.com,http://spring.io
  my-example1:
    '[foo.baz]' : bar